/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Bounce"

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }

    versionCatalogs {
        create("libs") {
        //    from(files("../gradle/libs.versions.toml"))
        }
    }
}
